# mappings between abbreviations used by SIS and longer descriptions

# all the mmappings from abbreviations to full-length descriptions
acad_group_mapping = {
    "LEAD": "Batten Leadership & Public Policy",
    "CGAS": "College & Graduate Arts & Sciences",
    "SCPS": "Continuing and Professional Studies",
    "GBUS": "Darden School of Business",
    "ENGR": "Engineering & Applied Science",
    "PROV": "Executive VP & Provost",
    "MCDG": "McIntire Darden Grad Business",
    "COMM": "McIntire School of Commerce",
    "MDS": "Medical School - BIMS/PHS",
    "ARCH": "School of Architecture",
    "DSCI": "School of Data Science",
    "EDUC": "School of Education & Human Development",
    "LAW": "School of Law",
    "MED": "School of Medicine",
    "NURS": "School of Nursing"
}


# traditional_requirement_mapping = {'SW': 'Second Writing Requirement',
#  'FL': 'Foreign Language Requirement',
#  'HNS': 'Historical Stdy/Non-West/SWR',
#  'HS': 'Historical Studies',
#  'HSNW': 'Historical Stdy & Non-Western',
#  'NW': 'Non-Western Perspectives',
#  'SWHS': 'Second Writing & Historical St',
#  'SWNW': 'Second Writing & None-Western'}


new_requirement_mapping = {'ASUD-AIP': 'Disciplines - Artistic, Interpretive, & Philosophical Inquiry',
 'ASUD-CMP': 'Disciplines - Chemical, Mathematical, and Physical Universe',
 'ASUD-CSW': 'Disciplines - Cultures & Societies of the World',
 'ASUR-R21C1': 'Literacies - First Writing Requirement',
 'ASUD-HP': 'Disciplines - Historical Perspectives',
 'ASUD-LS': 'Disciplines - Living Systems',
 'ASUQ-QCD': 'Literacies - Quantification, Computation, & Data Analysis',
 'ASUD-SS': 'Disciplines - Science and Society',
 'ASUR-R21C2': 'Literacies - Second Writing Requirement',
 'ASUD-SES': 'Disciplines - Social & Economic Systems',
 'ASUW-WL': 'Literacies - World Languages'}


acad_org_mapping = {'AAS': 'African-American and African Studies',
 'AIRS': 'Air Science',
 'ASL': 'American Sign Language',
 'AMST': 'American Studies',
 'ANTH': 'Anthropology',
 'APMA': 'Applied Mathematics',
 'AM': 'Applied Mechanics',
 'ALAR': 'Architecture & Landscape Architecture',
 'ARH': 'Architectural History',
 'ARCHDP': 'Architecture Department',
 'ART': 'Art',
 'ASTR': 'Astronomy',
 'BIOC': 'Biochemistry & Molecular Genetics',
 'BIOL': 'Biology',
 'BIOM': 'Biomedical Engineering',
 'BIMS': 'Biomedical Sciences',
 'BIOP': 'Biophysics',
 'CELL': 'Cell Biology',
 'CHE': 'Chemical Engineering',
 'CHEM': 'Chemistry',
 'CEE': 'Civil and Environmental Engineering',
 'CLAS': 'Classics',
 'COGS': 'Cognitive Science',
 'CGAS': 'College & Graduate Arts and Sciences',
 'CS': 'Computer Science',
 'EDIS': 'Curriculum, Instruction & Special Education',
 'ENGRD': 'Dean Engineering and Applied Science',
 'ARCHD': 'Dean of Architecture',
 'CGASD': 'Dean of Arts and Sciences',
 'COMMD': 'Dean of Commerce',
 'SCPSD': 'Dean of Continuing & Professional Studies',
 'DATAD': 'Dean of Data Science',
 'DATA': 'Data Science',
 'EDUCD': 'Dean of Education',
 'GBUSD': 'Dean of Graduate Business',
 'LAWD': 'Dean of Law',
 'MEDD': 'Dean of Medicine',
 'NURSD': 'Dean of Nursing',
 'DRAM': 'Drama',
 'EALC': 'East Asian Languages, Literatures & Cultures',
 'ECON': 'Economics',
 'ECE': 'Electrical & Computer Engineering',
 'STS': 'Engineering & Society',
 'ENGL': 'English',
 'EP': 'Engineering Physics',
 'ESE': 'Engineering Systems and Environment',
 'ESL': 'English as a Second Language',
 'EVSC': 'Environmental Sciences',
 'ETP': 'Environmental Thought and Practice',
 'PROVD': 'Executive VP and Provost',
 'FREN': 'French',
 'GERM': 'German',
 'HIST': 'History',
 'JWST': 'Jewish Studies',
 'EDHS': 'Human Services',
 'IMP': 'Interdisciplinary Major',
 'IDST': 'Interdisciplinary Studies',
 'EDKI': 'Kinesiology',
 'LAR': 'Landscape Architecture',
 'EDLF': 'Leadership, Foundation & Policy',
 'MSE': 'Material Science and Engineering',
 'MATH': 'Mathematics',
 'MCDG': 'McIntire Darden Grad Business',
 'MAE': 'Mechanical & Aerospace Engineering',
 'MDST': 'Media Studies',
 'MICR': 'Microbiology, Immunology, and Cancer Biology',
 'MESA': 'Middle Eastern & South Asian',
 'MISC': 'Military Science',
 'MUSI': 'Music',
 'NASC': 'Naval Science',
 'NESC': 'Neuroscience',
 'PATH': 'Pathology',
 'PHAR': 'Pharmacology',
 'PHIL': 'Philosophy',
 'PHYS': 'Physics',
 'PHY': 'Physiology',
 'PST': 'Political & Social Thought',
 'POLT': 'Politics',
 'PSYC': 'Psychology',
 'PHS': 'Public Health Sciences',
 'PPOL': 'Public Policy',
 'RELG': 'Religious Studies',
 'SLLT': 'Slavic',
 'SOC': 'Sociology',
 'SPAN': 'Spanish, Italian & Portuguese',
 'STAT': 'Statistics',
 'SIE': 'Systems and Information Engineering',
 'SYS': 'Systems and Information Engineering',
 'PLAN': 'Urban & Environmental Planning',
 'SWAG': 'Women, Gender & Sexuality'}