-- =======================
-- Core reference tables
-- =======================

CREATE TABLE terms (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR NOT NULL UNIQUE,     -- e.g., 'FA2025'
  name         VARCHAR,
  start_date   DATE,
  end_date     DATE,
  session      VARCHAR,                     -- 'Regular', 'Summer 1', etc.
  source_hash  VARCHAR,                     -- for idempotent upserts
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE course_catalog (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject         VARCHAR NOT NULL,         -- e.g., 'CS'
  catalog_number  VARCHAR NOT NULL,         -- e.g., '3100'
  title           VARCHAR NOT NULL,
  description     TEXT,
  min_credits     NUMERIC(3,1),
  max_credits     NUMERIC(3,1),
  attributes      JSONB,                    -- GenEd tags, level, etc.
  effective_start DATE,
  effective_end   DATE,
  sis_course_id   VARCHAR UNIQUE,           -- natural key from SIS, if available
  source_hash     VARCHAR,                  -- for idempotent upserts
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_catalog_unique_window UNIQUE (subject, catalog_number, effective_start)
);

CREATE INDEX idx_catalog_subject_number ON course_catalog (subject, catalog_number);

CREATE TABLE course_offerings (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_id          BIGINT NOT NULL REFERENCES terms(id) ON DELETE RESTRICT,
  catalog_id       BIGINT NOT NULL REFERENCES course_catalog(id) ON DELETE RESTRICT,
  topic            VARCHAR,
  grading_basis    VARCHAR,                 -- e.g., 'Graded', 'S/U'
  sis_offering_id  VARCHAR UNIQUE,
  source_hash      VARCHAR,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_offerings_term_catalog ON course_offerings (term_id, catalog_id);

CREATE TABLE sections (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offering_id        BIGINT NOT NULL REFERENCES course_offerings(id) ON DELETE CASCADE,
  component          VARCHAR NOT NULL,      -- LEC/LAB/DIS/etc.
  section_number     VARCHAR NOT NULL,      -- '001', 'A01'
  class_nbr          VARCHAR UNIQUE,        -- SIS class number if available
  total_seats        INT,
  waitlist_capacity  INT,
  status             VARCHAR,               -- 'Open','Closed','Cancelled'
  source_hash        VARCHAR,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_offering_section UNIQUE (offering_id, section_number)
);

CREATE INDEX idx_sections_offering ON sections (offering_id);

CREATE TABLE meeting_patterns (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id  BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  day_mask    VARCHAR,                      -- 'MTWRF' or another encoding/bitmask
  start_time  TIME,
  end_time    TIME,
  start_date  DATE,
  end_date    DATE,
  location    VARCHAR
);

CREATE INDEX idx_meeting_patterns_section ON meeting_patterns (section_id);

-- Consider monthly partitioning on captured_at if you poll often.
CREATE TABLE section_snapshots (
  section_id     BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  captured_at    TIMESTAMPTZ NOT NULL,
  seats_avail    INT,
  waitlist_avail INT,
  PRIMARY KEY (section_id, captured_at)
);

CREATE INDEX idx_snapshots_section ON section_snapshots (section_id);

-- =======================
-- Requisites
-- =======================

CREATE TABLE requisite_groups (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_id     BIGINT NOT NULL REFERENCES course_catalog(id) ON DELETE CASCADE, -- course that has the requisite
  req_type       VARCHAR NOT NULL,        -- 'pre' | 'co' | 'mutual_exclusion'
  n_of_m_count   SMALLINT,
  min_grade      VARCHAR,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_requisite_type CHECK (req_type IN ('pre','co','mutual_exclusion'))
);

CREATE INDEX idx_req_groups_catalog ON requisite_groups (catalog_id);

CREATE TABLE requisite_group_members (
  group_id            BIGINT NOT NULL REFERENCES requisite_groups(id) ON DELETE CASCADE,
  member_catalog_id   BIGINT NOT NULL REFERENCES course_catalog(id) ON DELETE RESTRICT,
  min_grade           VARCHAR,
  concurrency_allowed BOOLEAN,
  PRIMARY KEY (group_id, member_catalog_id)
);

CREATE INDEX idx_req_members_member ON requisite_group_members (member_catalog_id);

-- =======================
-- Degrees / Plans / Requirements
-- =======================

CREATE TABLE degrees (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  abbrev      VARCHAR NOT NULL,            -- 'B.A.'
  name        VARCHAR NOT NULL,            -- 'Bachelor of Arts'
  min_credits SMALLINT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE academic_plans (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sis_plan_code  VARCHAR UNIQUE,          -- 'CSCI-BS'
  title          VARCHAR NOT NULL,
  type           VARCHAR NOT NULL,        -- 'major'|'minor'|'certificate'|'concentration'
  degree_id      BIGINT REFERENCES degrees(id) ON DELETE RESTRICT,
  active_flag    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_plan_type CHECK (type IN ('major','minor','certificate','concentration'))
);

CREATE TABLE requirements (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id                  BIGINT NOT NULL REFERENCES academic_plans(id) ON DELETE CASCADE,
  code                     VARCHAR NOT NULL,    -- 'QUAL-WRT'
  title                    VARCHAR NOT NULL,
  description              TEXT,
  group_type               VARCHAR NOT NULL,    -- 'all'|'n_of_m'|'either_of'
  n_of_m_count             SMALLINT,
  min_credits              SMALLINT,
  min_courses              SMALLINT,
  min_grade                VARCHAR,
  double_counting_policy   VARCHAR,             -- 'allow'|'same_subject_only'|'disallow'
  seq                      SMALLINT,
  effective_start          DATE,
  effective_end            DATE,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_group_type CHECK (group_type IN ('all','n_of_m','either_of')),
  CONSTRAINT chk_double_counting CHECK (double_counting_policy IS NULL
    OR double_counting_policy IN ('allow','same_subject_only','disallow'))
);

CREATE INDEX idx_requirements_plan_seq ON requirements (plan_id, seq);

CREATE TABLE requirement_course_options (
  requirement_id  BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  catalog_id      BIGINT NOT NULL REFERENCES course_catalog(id) ON DELETE RESTRICT,
  notes           VARCHAR,
  grade_floor     VARCHAR,
  PRIMARY KEY (requirement_id, catalog_id)
);

CREATE INDEX idx_req_course_options_catalog ON requirement_course_options (catalog_id);

CREATE TABLE requirement_subreq_options (
  parent_req_id  BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  sub_req_id     BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  PRIMARY KEY (parent_req_id, sub_req_id)
);

CREATE INDEX idx_req_subreq_sub ON requirement_subreq_options (sub_req_id);

-- =======================
-- Students
-- =======================

CREATE TABLE users (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                   VARCHAR,
  email                  VARCHAR NOT NULL UNIQUE,
  default_active_plan_id BIGINT REFERENCES academic_plans(id) ON DELETE SET NULL,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE student_plans (
  student_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_id       BIGINT NOT NULL REFERENCES academic_plans(id) ON DELETE CASCADE,
  catalog_year  SMALLINT,
  status        VARCHAR NOT NULL,         -- 'active'|'completed'|'inactive'
  PRIMARY KEY (student_id, plan_id),
  CONSTRAINT chk_student_plan_status CHECK (status IN ('active','completed','inactive'))
);

CREATE INDEX idx_student_plans_student ON student_plans (student_id);

CREATE INDEX idx_student_plans_plan ON student_plans (plan_id);

CREATE TABLE student_course_attempts (
  student_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  offering_id   BIGINT NOT NULL REFERENCES course_offerings(id) ON DELETE RESTRICT,
  attempt_no    SMALLINT NOT NULL,
  status        VARCHAR NOT NULL,         -- 'in_progress'|'completed'|'withdrawn'|'transfer'|'test_credit'
  grade         VARCHAR,                  -- 'A','B-','P','W','IP', etc.
  credits       NUMERIC(3,1),
  grading_basis VARCHAR,                  -- 'graded','pnp','audit','su'
  source        VARCHAR,                  -- 'SIS','import','manual'
  PRIMARY KEY (student_id, offering_id, attempt_no),
  CONSTRAINT chk_attempt_status CHECK (status IN ('in_progress','completed','withdrawn','transfer','test_credit'))
);

CREATE INDEX idx_attempts_student ON student_course_attempts (student_id);

CREATE INDEX idx_attempts_offering ON student_course_attempts (offering_id);

CREATE TABLE student_exceptions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  requirement_id BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
  type           VARCHAR NOT NULL,        -- 'waiver'|'substitution'
  payload        JSONB,
  approved_by    VARCHAR,
  approved_at    TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_exception_type CHECK (type IN ('waiver','substitution'))
);

CREATE INDEX idx_exceptions_student ON student_exceptions (student_id);

CREATE INDEX idx_exceptions_requirement ON student_exceptions (requirement_id);

-- =======================
-- Cross-listings & Equivalencies
-- =======================

CREATE TABLE course_crosslistings (
  catalog_id      BIGINT NOT NULL REFERENCES course_catalog(id) ON DELETE CASCADE,
  subject         VARCHAR NOT NULL,
  catalog_number  VARCHAR NOT NULL,
  PRIMARY KEY (catalog_id, subject, catalog_number)
);

CREATE INDEX idx_cross_subject_number ON course_crosslistings (subject, catalog_number);

CREATE TABLE course_equivalencies (
  a_id       BIGINT NOT NULL REFERENCES course_catalog(id) ON DELETE CASCADE,
  b_id       BIGINT NOT NULL REFERENCES course_catalog(id) ON DELETE CASCADE,
  rule_notes TEXT,
  PRIMARY KEY (a_id, b_id),
  CONSTRAINT chk_equiv_not_self CHECK (a_id <> b_id)
);